name: CI/CD for ml_pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Docker Image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ml_pipeline:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/ml_pipeline:${{ github.sha }}

      - name: Deploy ml_pipeline
        run: |
          docker pull ghcr.io/${{ github.repository }}/ml_pipeline:${{ github.sha }}
          docker run --name ml_pipeline -d ghcr.io/${{ github.repository }}/ml_pipeline:${{ github.sha }}
